apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: appmesh-bookinfo
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::927411430400:role/eksctl-dma-m3cedeveuc1-addon-iamserviceaccou-Role1-4L5PZ7TN307M
  name: appmesh-bookinfo